before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
archives:
  -
    files:
      - rules/*
      - etc/*
      - var/*
      - filter.bpf
      - config.yml
      - Dockerfile
      - Makefile
    wrap_in_directory: true
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
