package events

import (
	"time"
)

// BaseEvent described the common structure to all the events generated by the received packets
type BaseEvent struct {
	IPVersion  uint
	Tags       Tags
	Kind       string
	SourceIP   string
	DestPort   uint16
	Session    string
	Timestamp  time.Time
	Additional map[string]string
	Event
}

// Tags is an abstraction of map[string]interface{} allowing for the use of a set-like structure and a more graceful
// conversion to array
type Tags map[string]interface{}

// GetKind fetches the Kind of an event
func (ev BaseEvent) GetKind() string {
	return ev.Kind
}

// GetSourceIP fetches the SourceIP of an event
func (ev BaseEvent) GetSourceIP() string {
	return ev.SourceIP
}

// GetDestPort fetches the DestPort of an event
func (ev BaseEvent) GetDestPort() uint16 {
	return ev.DestPort
}

// AddAdditional fetches the Additional values of an event
func (ev *BaseEvent) AddAdditional(add map[string]string) {
	for key, values := range add {
		ev.Additional[key] = values
	}
}

// AddTags add the given tag array to the event's tags
func (ev *BaseEvent) AddTags(tags []string) {
	for _, tag := range tags {
		ev.Tags[tag] = struct{}{}
	}
}

// ToArray converts an optimized Tags to an array
func (t *Tags) ToArray() []string {
	var ret []string
	for tag := range *t {
		ret = append(ret, tag)
	}

	return ret
}
